version: 0.2

env:
  variables:
    REPOSITORY_URI: 940482450120.dkr.ecr.ap-south-1.amazonaws.com/my-react-app
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing latest npm...
      - npm install -g npm@latest

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Pulling latest image for cache...
      - docker pull $REPOSITORY_URI:$IMAGE_TAG || true

  build:
    commands:
      - echo Building Docker image...
      - docker build --cache-from $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"my-react-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.npm/**/*'
